import { ParsedCall } from '@/types';

const now = Date.now();
const ago = (minutes: number) => new Date(now - minutes * 60 * 1000).toISOString();

export const MOCK_CALLS: ParsedCall[] = [
  {
    id: 'mock-01',
    phone: '+34 91 234 5678',
    contactName: 'Carlos Jiménez',
    companyName: 'Plastika Solutions S.L.',
    status: 'completed',
    outcome: 'escalated',
    phaseReached: 5,
    duration: 372,
    timestamp: ago(8),
    completedAt: ago(2),
    toolsCalled: ['record_price_expectation', 'escalate_to_commercial'],
    negotiationResult: 'aligned',
    clientPrice: '880',
  },
  {
    id: 'mock-02',
    phone: '+34 93 456 7890',
    contactName: 'Ana González',
    companyName: 'Polímeros Ibérica S.A.',
    status: 'completed',
    outcome: 'closed',
    phaseReached: 5,
    duration: 275,
    timestamp: ago(22),
    completedAt: ago(18),
    toolsCalled: ['record_price_expectation', 'close_polite'],
    negotiationResult: 'out_of_market',
    closeReason: 'fuera_de_mercado',
    clientPrice: '720',
  },
  {
    id: 'mock-03',
    phone: '+34 96 345 6789',
    contactName: 'Roberto Moreno',
    companyName: 'Quimiplás Valencia S.L.',
    status: 'completed',
    outcome: 'escalated',
    phaseReached: 5,
    duration: 348,
    timestamp: ago(35),
    completedAt: ago(30),
    toolsCalled: ['record_price_expectation', 'escalate_to_commercial'],
    negotiationResult: 'negotiable',
    clientPrice: '810',
  },
  {
    id: 'mock-04',
    phone: '+34 91 567 8901',
    contactName: 'Pedro Fernández',
    companyName: 'Industrias Marín S.A.',
    status: 'completed',
    outcome: 'callback',
    phaseReached: 3,
    duration: 130,
    timestamp: ago(48),
    completedAt: ago(46),
    toolsCalled: ['schedule_callback'],
    callbackDate: '28/02/2026',
    callbackTime: 'mañana a las 10:00',
    callbackNotes: 'Solicita información por email antes de continuar',
  },
  {
    id: 'mock-05',
    phone: '+34 94 678 9012',
    contactName: undefined,
    companyName: 'TecnoPlast Madrid S.L.',
    status: 'completed',
    outcome: 'voicemail',
    phaseReached: 0,
    duration: 8,
    timestamp: ago(55),
    completedAt: ago(55),
    toolsCalled: ['report_voicemail'],
  },
  {
    id: 'mock-06',
    phone: '+34 93 789 0123',
    contactName: 'María López',
    companyName: 'Eurocomposit Barcelona',
    status: 'completed',
    outcome: 'decision_maker',
    phaseReached: 1,
    duration: 115,
    timestamp: ago(70),
    completedAt: ago(68),
    toolsCalled: ['request_decision_maker_contact'],
    decisionMakerName: 'Javier Ruiz',
  },
  {
    id: 'mock-07',
    phone: '+34 91 890 1234',
    contactName: 'José García',
    companyName: 'Grupo Polimax S.L.',
    status: 'completed',
    outcome: 'closed',
    phaseReached: 2,
    duration: 47,
    timestamp: ago(85),
    completedAt: ago(84),
    toolsCalled: ['close_polite'],
    closeReason: 'sin_interes',
  },
  {
    id: 'mock-08',
    phone: '+34 94 901 2345',
    contactName: 'Carmen Ruiz',
    companyName: 'Plásticos del Norte S.L.',
    status: 'completed',
    outcome: 'escalated',
    phaseReached: 5,
    duration: 443,
    timestamp: ago(100),
    completedAt: ago(93),
    toolsCalled: ['record_price_expectation', 'escalate_to_commercial'],
    negotiationResult: 'aligned',
    clientPrice: '895',
  },
  {
    id: 'mock-09',
    phone: '+34 96 012 3456',
    contactName: 'Luis Herrera',
    companyName: 'Composites Levante',
    status: 'completed',
    outcome: 'closed',
    phaseReached: 3,
    duration: 192,
    timestamp: ago(115),
    completedAt: ago(112),
    toolsCalled: ['close_polite'],
    closeReason: 'sin_consumo_estireno',
  },
  {
    id: 'mock-10',
    phone: '+34 91 123 4567',
    contactName: 'Antonio Sánchez',
    companyName: 'Iberquim S.A.',
    status: 'completed',
    outcome: 'callback',
    phaseReached: 4,
    duration: 292,
    timestamp: ago(130),
    completedAt: ago(125),
    toolsCalled: ['schedule_callback'],
    callbackDate: '02/03/2026',
    callbackTime: 'próxima semana',
    callbackNotes: 'Interesado, quiere consultar con dirección',
  },
  {
    id: 'mock-11',
    phone: '+34 93 234 5678',
    contactName: 'Elena Navarro',
    companyName: 'Polisol Bilbao S.L.',
    status: 'completed',
    outcome: 'qualified',
    phaseReached: 4,
    duration: 215,
    timestamp: ago(145),
    completedAt: ago(141),
    toolsCalled: ['record_qualified_lead'],
    purchaseType: 'contrato_anual',
    annualConsumption: '500 TM/año',
  },
  {
    id: 'mock-12',
    phone: '+34 95 345 6789',
    contactName: undefined,
    companyName: 'Plastiglas Sevilla',
    status: 'completed',
    outcome: 'voicemail',
    phaseReached: 0,
    duration: 6,
    timestamp: ago(160),
    completedAt: ago(160),
    toolsCalled: ['report_voicemail'],
  },
  {
    id: 'mock-13',
    phone: '+34 91 456 7890',
    contactName: 'Rosa Jiménez',
    companyName: 'Quitex International',
    status: 'completed',
    outcome: 'decision_maker',
    phaseReached: 1,
    duration: 145,
    timestamp: ago(175),
    completedAt: ago(173),
    toolsCalled: ['request_decision_maker_contact'],
    decisionMakerName: 'Fernando Castillo',
  },
  {
    id: 'mock-14',
    phone: '+34 93 567 8901',
    contactName: 'David Martín',
    companyName: 'Araplás Barcelona',
    status: 'completed',
    outcome: 'escalated',
    phaseReached: 5,
    duration: 365,
    timestamp: ago(190),
    completedAt: ago(184),
    toolsCalled: ['record_price_expectation', 'escalate_to_commercial'],
    negotiationResult: 'negotiable',
    clientPrice: '830',
  },
  {
    id: 'mock-15',
    phone: '+34 91 678 9012',
    contactName: 'Sofía Pérez',
    companyName: 'Moldeados Castilla S.A.',
    status: 'completed',
    outcome: 'closed',
    phaseReached: 5,
    duration: 317,
    timestamp: ago(210),
    completedAt: ago(205),
    toolsCalled: ['record_price_expectation', 'close_polite'],
    negotiationResult: 'out_of_market',
    closeReason: 'fuera_de_mercado',
    clientPrice: '745',
  },
  {
    id: 'mock-live',
    phone: '+34 96 789 0123',
    contactName: 'Miguel Torres',
    companyName: 'Poliform Valencia',
    status: 'running',
    outcome: 'in_progress',
    phaseReached: 3,
    duration: undefined,
    timestamp: ago(3),
    toolsCalled: [],
  },
];
